#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)
require 'hdo/import'
args = ARGV.dup # get args before loading env

require File.expand_path('../../config/environment',  __FILE__)
require 'hdo/storting_importer'

cli = Hdo::Import::CLI.new(args) 
cli.run
