#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)
require 'hdo/import'
cli = Hdo::Import::CLI.new(ARGV) # parse args before loading env

require File.expand_path('../../config/environment',  __FILE__)
require 'hdo/storting_importer'

cli.run
